[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.4", features = ["http2"] }
config = "0.13.1"
serde = { version = "1", features = ["derive"] }
time = "0.3.31"
tokio = { version = "1.34.0", features = ["full"] }
tower-http = { version = "0.5.1", features = ["trace"] }
uuid = { version = "1.6.1", default-features = false, features = ["serde", "v4"] }

[dependencies.sqlx]
version = "0.7"
default-features = false
features = [
	"runtime-tokio",
	"tls-rustls",
	"macros",
	"postgres",
	"uuid",
	"time",
	"migrate"
]

[dev-dependencies]
reqwest = "0.11.22"
