[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["http2", "headers"] }
config = "0.13.1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.34.0", features = ["full"] }

[dependencies.sqlx]
version = "0.7"
default-features = false
features = [
	"runtime-tokio",
	"tls-rustls",
	"macros",
	"postgres",
	"uuid",
	"time",
	"migrate"
]

[dev-dependencies]
reqwest = "0.11.22"
