[application]
port = 8000

[database]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "password"
name = "newsletter"

[email_client]
base_url = "localhost"
sender_email = "john@test.com"
authorization_token = "super-secret-token"
timeout_millis = 10000
